services:
  - type: cron
    name: ingrosmart-agent-docker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt
    schedule: "*/30 * * * *"
    envVars:
      - key: INGRO_USER
        sync: false
      - key: INGRO_PASS
        sync: false
      - key: TARGET
        value: fs
      - key: LOG_LEVEL
        value: info
    autoDeploy: true
